### ISSUE TITLE
Does not work with latest version of pydantic

### ISSUE THREAD

**Issue by noenfugler** [dcferreira/pylemmy#18]
in the latest version of pedantic, urllib.parse.urljoin expects two string args, but pylemmy passes a URL and a str in line 66 of lemmy.py

**Comment by dcferreira** [comment]
I had a quick look at this issue. Unfortunately the changes to support pydantic v2 are a bit more than that.
I fixed that specific issue, and a bunch more popped up, it's unclear to me how much needs changing.

For now I'll just limit the pydantic version in the dependencies and push a new version (v0.0.6).
If you happen to have the time, it would be great to support pydantic v2! They have [a guide to upgrade from v1 to v2](https://docs.pydantic.dev/latest/migration/).

I'll leave this issue open.

**Comment by maparent** [comment]
Addressed in https://github.com/dcferreira/pylemmy/pull/27

**Comment by maparent** [comment]
Which is now merged. Pydantic 2 is now expected.
