### ISSUE TITLE
Allow streaming over multiple communities

### ISSUE THREAD

**Issue by dcferreira** [dcferreira/pylemmy#2]
It would be great to be able to iterate over all the posts/comments in a multitude of communities.
I see it working as something like this:

```python
lemmy.get_community(["community1", "community2", ...]).stream.get_posts()
```

At the moment Lemmy doesn't have the equivalent of multi-reddits (but they might eventually https://github.com/LemmyNet/lemmy/issues/818).
However, it should still be possible to do it by doing round-robin requests to a bunch of communities.

**Comment by noenfugler** [comment]
Support this.
