### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by dcferreira** [dcferreira/pylemmy#20]
Currently the integration tests are failing, and I'm not sure why. Some investigation is needed here.

**Comment by noenfugler** [comment]
Worked fine for the. most recent pull request

**Comment by dcferreira** [comment]
Oh I think I fixed at the time? Closing now, thanks for checking @noenfugler :)

**Comment by dcferreira** [comment]
They are still failing actually, reopening this. It seems to fail at authentication, but I didn't look into why.

**Comment by maparent** [comment]
This got corrected with my work on authentication in the #28 PR.
Tests now pass (except on 3.7, for other reasons.)
Closing for now.
