### ISSUE TITLE
Add a 'create_report' method to the post Class.

### ISSUE THREAD

**Issue by noenfugler** [dcferreira/pylemmy#3]
It would be awesome to have a create_report method in the Post class.  This library seems to be the most stable Python Lemmy API library, and I'm building a moderator bot, but need to flag posts for review by a human.  Happy to help with testing etc..

**Comment by dcferreira** [comment]
Great that you're building a moderator bot, that was actually my goal with this library :)

Yes please testing would be very useful.
If you can come up with some unit tests and more integration tests, that would also be super useful, as at the moment it's very incomplete.

This should be implemented in v0.0.3, to be released in a few minutes (as soon as the CI pipelines pass).

**Comment by noenfugler** [comment]
OK.  Note that it appears that Post reports and Comment reports are two entirely methods, each on their respective class.

**Comment by noenfugler** [comment]
I've got the bot up and running at the moment.  I'll let you know if I find any bugs.

**Comment by dcferreira** [comment]
Regarding the post vs comment, I think I did it correctly in the code. Let
me know if I missed something!

Good to hear it's running :)

**Comment by noenfugler** [comment]
Did you merge my pull request or use your own?  If it was yours I may have to update my bot.
