### ISSUE TITLE
Possibility of a get_content method which returns both posts and comments.

### ISSUE THREAD

**Issue by noenfugler** [dcferreira/pylemmy#6]
To avoid having to have two bots running, one checking posts and one checking comments.

**Comment by dcferreira** [comment]
Do you mean in the stream (like in `Community.stream.get_posts()`)? Or when you just call it once (`Community.get_posts()`).

If you mean in the stream, the implementation is probably the same as in #2 (allow streaming over a list of things).
I don't think I'll have time to implement that in the next few days, but if you're willing to do it I'd be happy to accept the PR.

If it's the 2nd option, I could implement that today.

**Comment by noenfugler** [comment]
I was thinking a stream of both posts and comments, but I'm happy to work with whatever you come up with.

**Comment by dcferreira** [comment]
Yeah I agree that makes the most sense. I don't think I'll have time to do it in the next few days though.

If I start working on it, I'll leave a comment here.

**Comment by dcferreira** [comment]
I found some time now, will give it a try.

**Comment by dcferreira** [comment]
Closed in #8 .
